import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import { Routes, Route, } from "react-router-dom";
import { HashRouter as Router } from "react-router-dom";
import Home from './components/pages/home/home';
import Layout from './components/layout/layout';
import LoginPage from './components/pages/users/loginpage';
import ArticleListPage from './components/pages/articles/articleListPage';
import TutorialListPage from './components/pages/articles/tutorialListPage';
import ArticleViewPage from './components/pages/articles/articleViewPage';
import NewArticlePage from './components/pages/articles/newArticle';
import GalleryPage from './components/pages/gallery/galleryPage';
createRoot(document.getElementById('root')).render(_jsx(StrictMode, { children: _jsx(Router, { children: _jsx(Routes, { children: _jsxs(Route, { path: "/", element: _jsx(Layout, {}), children: [_jsx(Route, { index: true, element: _jsx(Home, {}) }), _jsx(Route, { path: "home", element: _jsx(Home, {}) }), _jsx(Route, { path: "login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "articleList/:page?", element: _jsx(ArticleListPage, {}) }), _jsx(Route, { path: "tutorialList/:page?", element: _jsx(TutorialListPage, {}) }), _jsx(Route, { path: "articles/:id", element: _jsx(ArticleViewPage, {}) }), _jsx(Route, { path: "articleCreate", element: _jsx(NewArticlePage, {}) }), _jsx(Route, { path: "gallery/:page?", element: _jsx(GalleryPage, {}) })] }) }) }) }));
